#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
sum=0
item1=1
item2=2
item3=0
sum=2
while item3<4000000 :
	item3=item1+item2
	if item3%2==0:
		sum+=item3
	item1=item2
	item2=item3
	
if item3%2==0:
	sum-=item3
print sum